version: '3'

services:
  spring-boot-app:
    image: Chanyong-Park/webflux:0.0.2
    container_name: webfluxByDockerCompose
    ports:
      - "8070:8080"
    environment:
      - WHICH_PROFILE=staging